services:
  postgres:
    image: postgres:18
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_iban_dev
      POSTGRES_DB: iban
    volumes:
      - pgdata:/var/lib/postgresql
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"

volumes:
  pgdata:
