spring.datasource.url=jdbc:postgresql://localhost:5432/iban
spring.datasource.username=postgres
spring.datasource.password=postgres_iban_dev
spring.datasource.driver-class-name=org.postgresql.Driver

# fine for dev for prod should be validate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
